### ISSUE TITLE
How can i remove the line that is currently drawn and than draw a new one inside a function ?

### ISSUE THREAD

**Issue by esliagolli** [anseki/leader-line#115]
Lets say Im inside my function where the goal is that each time i click a specified element a line is drawn but the old one gets deleted.

`function drawLine(elementId) {
        let startElement = document.getElementById(elementID);
        let endElement = document.getElementById('someID');
        let line = new LeaderLine(startElement, endElement, {color: 'red', size: 5, hide: true});
//Tried line.hide() here
line.hide();
//here waiting for ajax call to finish.

line.show();
}`

This is working for drawing the new line but is not deleting the old one.

**Comment by anseki** [comment]
Hi @esliagolli, thank you for the comment.
You can remove a line via [`remove`](https://anseki.github.io/leader-line/#remove) method.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.

**Comment by humblecoder** [comment]
This doesn't seem to work.  Admittedly, I'm using [leader-line-vue](https://www.npmjs.com/package/leader-line-vue).  That said, it seems like we should be able to append a "class" or "id" attribute to a line via the API.  Is there a particular reason that sort of functionality isn't exposed?

As an example,  I have a single interface with multiple components that make use of LeaderLine within their own contexts.  I need the ability to manipulate all of one group without manipulating any of another group.  If I can't manage that via the library, then I'd at least like access to the DOM in a contextually specific manner.

Additionally, the fact that the SVGs are drawn outside their respective "containers" presents further "access" issues.

**Comment by anseki** [comment]
Hi @humblecoder, thank you for the comment.
Sorry, I don't know the "leader-line-vue", that is not my library.
Please ask to the author of the "leader-line-vue" about the library.

**Comment by humblecoder** [comment]
@anseki, so, I switched to `leader-line` rather than `leader-line-vue` and used `LeaderLine` (per the documentation).  Same behavior.  I must refresh in some manner or the items aren't successfully removed from the DOM.  I'm simply collecting them in an array, then when I'm finished with them, I'm `pop`ing them off the array and `.remove()`ing them.  They don't actually do away until a page refresh or navigating away then coming back.

I'm more than happy to search the source, but if you have a specific obvious thing I might be missing, that would be helpful as well.  Either way, thanks.

**Comment by anseki** [comment]
Sorry, I couldn't understand that well.
Could you show me an example by using e.g. https://jsfiddle.net/ ?
Also, is that related to this issue that was made by @esliagolli?
You should make new issue if that is another topic.
