### ISSUE TITLE
Possible to adjust 'grid' size? for line 

### ISSUE THREAD

**Issue by calumk** [anseki/leader-line#133]
Is it possible to adjust the 'grid' size used to draw the lines?
I notice when two elements are close to each other, the grid style line will do a "loop"

![tight](https://user-images.githubusercontent.com/1183991/82790110-6f087e80-9e63-11ea-9d38-5369c164438a.jpg)

A similar problem happens with fluid, the curve is too great, it goes back on itself
![Screenshot 2020-05-25 at 08 36 09](https://user-images.githubusercontent.com/1183991/82789780-cf4af080-9e62-11ea-9966-04d2d7a95de9.JPG)

**Comment by calumk** [comment]
I managed to fix the problem by altering the file and re-building. 
I don't know if it is possible to adjust these values without editing source? 

 ```
// new 
MIN_GRAVITY = 20, MIN_GRAVITY_SIZE = 4, MIN_GRAVITY_R = 5,
 MIN_OH_GRAVITY = 30, MIN_OH_GRAVITY_OH = 8, MIN_OH_GRAVITY_R = 3.75,
MIN_ADJUST_LEN = 10, MIN_GRID_LEN = 5,

// old
// MIN_GRAVITY = 80, MIN_GRAVITY_SIZE = 4, MIN_GRAVITY_R = 5,
// MIN_OH_GRAVITY = 120, MIN_OH_GRAVITY_OH = 8, MIN_OH_GRAVITY_R = 3.75,
// MIN_ADJUST_LEN = 10, MIN_GRID_LEN = 30,
```

**Comment by anseki** [comment]
Hi @calumk, thank you for the comment.
Can [`startSocketGravity`/`endSocketGravity` options](https://anseki.github.io/leader-line/#startsocketgravity-endsocketgravity) help you?

**Comment by calumk** [comment]
I think it would help for the fluid path, but not the grid path? 
Unless i am reading the source incorrectly?

**Comment by anseki** [comment]
Sorry, I can't understand what is problem because almost all `path` types should not draw the closest line between elements that are close to each other. LeaderLine should make a space for drawing a line that has specific `path`. The `straight` draws the closest line.
Of course you can customize that for your project if you want.

**Comment by anseki** [comment]
For example: https://jsfiddle.net/d0mv2caL/
This line also becomes a loop. I think that this is correct behavior, and this has no problem.

**Comment by calumk** [comment]
I think it is a preference of the user how the style of the line should be, 
For your example, I do not think loop is correct, i think a small curve (no loop) would be better, 
But i understand this is user preference.

For now, I have resolved the issue by altering the MIN_GRID_LEN setting, and rebuilding the project.

So I would suggest making MIN_GRID_LEN editable 
```
line.setOptions({
    minGridLength: 5,
});
```

but for now i am happy to close issue

**Comment by anseki** [comment]
Sorry, I can't understand why the loop is problem, and it can't avoid the loop perfectly.
I think that it is better that user adjust something (position, path, parameters, etc.) rather than the library breaks own work (i.e. `path` style).
Thank you for your suggestion. :smile: 
So, could you close this issue if it was solved?
