### ISSUE TITLE
leader-line to png

### ISSUE THREAD

**Issue by rokmesojedec** [anseki/leader-line#134]
This is not directly an issue with your library. But, I would still ask you, the author, if you know of any good solutions for saving the html with leader line svg into an image (png or jpg). 

I tried html2canvas, but svg isn't supported.

Thank you in advance.

**Comment by anseki** [comment]
Hi @rokmesojedec, thank you for the comment.
I couldn't understand the "saving the html with leader line svg into an image" that you said.
If you want to convert a SVG image to a PNG image, you can find many tools and libraries in internet.
If you want to save LeaderLine objects into HTML, that is impossible.
If you want to save a HTML page including LeaderLine objects into a PNG image, you can do that by e.g. Chromium.

**Comment by rokmesojedec** [comment]
What I meant is, if you know of a good way of how to programmatically create a screenshot of an app which contains svg created with LeaderLine objects. I know I can use the print command with chromium and save it into an image. But I wanted to know if you knew of a better, more user-friendly solution. 

In any case, thank you for answering and providing us this wonderful library!

**Comment by anseki** [comment]
Best way to save a HTML page including LeaderLine objects into a PNG image programmatically I think is headless Chromium because a rendering engine such as Blink is the most suitable program to render HTML even if that does not include SVG.
You can use library to control headless Chromium easily, such as [Puppeteer](https://github.com/puppeteer/puppeteer).

**Comment by rokmesojedec** [comment]
Thanks a lot. I think this is what I'm looking for :)

**Comment by anseki** [comment]
:smile:
