### ISSUE TITLE
Leader line position not correct in case parent has overflow

### ISSUE THREAD

**Issue by siddhartha-gupta** [anseki/leader-line#166]
Firstly, thanks for such a beautiful library.

I'm trying to draw a leader line between 2 table rows. But tables has overflow, due to which leader line position is not correct. Please refer to jsfiddle

https://jsfiddle.net/6t7bjp28/17/

- 1st line should start from left, by touching left table
- 2nd line should stop at bottom of 2nd table

Please let me know available options to solve this.

**Comment by anseki** [comment]
Hi @siddhartha-gupta, thank you for the comment.
Do you mean that you want to specify a side of the element the leader line connects?
If so, specify [`startSocket`/`endSocket`](https://anseki.github.io/leader-line/#startsocket-endsocket) options.

**Comment by siddhartha-gupta** [comment]
Thanks for the prompt reply.

I want to connect 'Table1 Row' to 'Table2 Row'. Due to overflow in table width and height line position is not correct.

Expected - ![Screenshot 2020-10-20 at 9 27 23 PM](https://user-images.githubusercontent.com/1487517/96612605-93399000-131b-11eb-8c34-f273dc3274a1.png)

Current - ![Screenshot 2020-10-20 at 9 26 07 PM](https://user-images.githubusercontent.com/1487517/96612644-9fbde880-131b-11eb-937d-54a8b9700753.png)

**Comment by anseki** [comment]
I see.
Since you specified the `overlay` that is a value for only Blink, I didn't see that figure that you said by other browsers.
![ss01](https://user-images.githubusercontent.com/4763469/96665970-1943ee00-1391-11eb-8aee-d2c325eda3e2.png)

Anyway, the lines seem to be positioned correctly.
I can't understand your expected result. Why the line that was given `row6` is connected to third row? The line should connect to the 6th row because you specified the 6th row. Then the line is connected to that correctly.

**Comment by uds214125** [comment]
@anseki an awesome library which I found as an opensource. 

my concern was to dynamically draw the line between the tables based on the condition instead of hard-coded "element's id".

what I mean is that 
![image](https://user-images.githubusercontent.com/17702550/97045970-49a7aa00-1594-11eb-8597-4027d9093a23.png)

please give your thought

**Comment by anseki** [comment]
Hi @uds214125, thank you for the comment.
Could you make new issue for another topic?

**Comment by uds214125** [comment]
> Hi @uds214125, thank you for the comment.
> Could you make new issue for another topic?

yeah sure

**Comment by siddhartha-gupta** [comment]
Hi @anseki,

Thanks for your inputs. I've managed to solve my issues using 'LeaderLine.pointAnchor' with scroll event listeners in real codebase.
A small mock of the same - https://jsfiddle.net/sid2varun/bvjr8n05/47/

Once again, thanks for such a beautiful library. Please close this issue

**Comment by anseki** [comment]
Ok, I will close this issue instead of you.
FYI, your example was shown:
![ss01](https://user-images.githubusercontent.com/4763469/97109857-032f8800-1719-11eb-81cd-20a0a7bc516a.png)
