### ISSUE TITLE
How can i adjust overlapping of lines

### ISSUE THREAD

**Issue by uds214125** [anseki/leader-line#172]
For example:  https://stackblitz.com/edit/angular-leader-rrvdhy-u4kfa3

lines from table1 to table3.

**Comment by anseki** [comment]
Hi @uds214125, thank you for the comment.
I think that you cut corners too much, then nobody can answer that.
Could you explain about the issue?
Also, what does “from table1 to table3” mean? (i.e. are those indexes?)

**Comment by uds214125** [comment]
My bad. I did not explain it.

"from table1 to table3", I meant to this 
![image](https://user-images.githubusercontent.com/17702550/97407486-ba4a2000-1920-11eb-8aa3-5ec533333010.png)

lines from "profile" to "meta" and "account" to "meta"  are drawing over the "account" and "address" tables. 

How can I draw the line which will draw the line like this 
![image](https://user-images.githubusercontent.com/17702550/97408382-fe89f000-1921-11eb-89e4-b12eb3cf53d8.png)

**Comment by anseki** [comment]
I see.
It seems that you mistook the "table4" for the "table3".
An important point is that, since you gave `display: flex` to the tables, those are positioned flexibly.
For example, this is view via my computer:
![ss01](https://user-images.githubusercontent.com/4763469/97459534-38d5aa80-197f-11eb-9201-cdc63ad178ae.png)

That is, you can adjust lines by specifying fixed position to each table.
For example:
![ss02](https://user-images.githubusercontent.com/4763469/97459598-48ed8a00-197f-11eb-9999-e6ac901fec4c.png)

Or, you can specify a transparent color to allow you to look tables even if the lines overlap those.
![ss03](https://user-images.githubusercontent.com/4763469/97460261-f19be980-197f-11eb-9547-c4bd86f45c03.png)
Or, you can specify [`path`](https://anseki.github.io/leader-line/#path) and others to adjust lines.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
