### ISSUE TITLE
A route of grid line

### ISSUE THREAD

**Issue by K-actus** [anseki/leader-line#175]
Hi.

When I used grid line in table, I found a strange behavior.
It is an example.
https://jsfiddle.net/s9q264nv/

When I draw a line from 'A' to 'D' or 'E', the arrow made an unnecessary loop path.
Is it based on the technical specifications?
Should I use not 'grid' but 'straight'?

**Comment by anseki** [comment]
Hi @K-actus, thank you for the comment.
That loop is necessary path, and that is correct behavior because LeaderLine tries to keep a measurable size of `grid`.
You can adjust the path via options if you need.
For example: https://jsfiddle.net/hp7vzqbo/
Note that I don't know a line which you want. Is the example above your expected result?

**Comment by K-actus** [comment]
Hi, @anseki .
Yes, this is it.
Thank you for great answering.
I close this issue.

**Comment by anseki** [comment]
:smile:
