### ISSUE TITLE
Is there any way to add an ID to leader line?

### ISSUE THREAD

**Issue by ndthanh** [anseki/leader-line#18]
Is there any way to add an ID to leader line?

Thank you.

**Comment by anseki** [comment]
Hi @ndthanh, thank you for the comment.
You can add an ID to a SVG element via `id` property.
Sorry if I misunderstood your question.

**Comment by ndthanh** [comment]
Hi @anseki,

first of all, thank you for your wonderful library. Sorry for not beining specific enough. Is there any way to add an ID to leader-line created by your leader-line library when the line is created like this:

```
  line = new LeaderLine(
  	target2, 
  	target1,
    {
    	startPlug: 'square',
    	endPlug: 'square', 
    	startPlugColor: '#1a6be0',
        endPlugColor: '#1efdaa',
	gradient: true,
	id: "line-test"   // is there any way to add id to this LeaderLine like this? Thank you :)
    });
```

**Comment by anseki** [comment]
Hmm..., what is "ID" concretely?
Simply, you can add any property to an Object in ECMAScript.
For example:

```js
line = new LeaderLine(target1, target2);
line.id = 'line-test'
console.log(line.id); // The 'line-test' is shown.
```

**Comment by ndthanh** [comment]
Actually, I would like a way to add an id as attribute to the LeaderLine SVG Element, but I think line.id could be sufficient for now. Thank you very much.

**Comment by anseki** [comment]
I'm happy if I could help you. :smile: 
BTW, as I said (https://github.com/anseki/leader-line/issues/18#issuecomment-408396125), you can add an ID to a SVG element via id property of the element.

**Comment by sean-mcclure** [comment]
I get undefined, as though new Leaderline does not return anything. 

I would really help to be able to add an id to the actual leaderline itself, at creation time, so that it could be reference. Just another property along with size, color, etc.

**Comment by anseki** [comment]
Hi @sean-mcclure, thank you for the comment.
Could you show me an example to reproduce that the `undefined` is returned?
Usually, an ID is not used to reference to that because an instance can be used to do anything (and anytime).

**Comment by AlexSkrypnyk** [comment]
The object returned by the `LeaderLine()` constructor does not have a public property referencing a DOM element, so it is not possible to retrieve a DOM object created by the class.

Instead, one should retrieve that *last* added `.leader-line` element from the DOM to add the required attributes to the SVG.

So:
1. Create a line element `var line = new LeaderLine();`
2. `$('body>.leader-line:last-child').data('myid', 'myval');`
           
@anseki 
Could you please consider adding this to the docs because people keep asking the same thing over and over again (I counted 5 issues in the queue).

**Comment by anseki** [comment]
Hi @AlexSkrypnyk, thank you for the comment.
That should not be added to the document because that is not supported and that is deprecated, as mentioned in the past issues over and over again.
Thank you for your suggestion. :smile:

**Comment by AlexSkrypnyk** [comment]
@anseki 
I'm confused.

What is not supported and what is deprecated? In other issues you are suggesting to use this method.

Can you please provide a specific instruction on how to add custom properties to SVGs.

**Comment by anseki** [comment]
No, I didn't suggest that because that is not supported and that is deprecated.

**Comment by AlexSkrypnyk** [comment]
@anseki 
Can you please provide a specific instruction on how to add custom properties to SVGs.

**Comment by anseki** [comment]
See: https://github.com/anseki/leader-line/issues/18#issuecomment-408406267

**Comment by sean-mcclure** [comment]
@AlexSkrypnyk you can keep track of the added lines by storing your own `id` on the created SVG. 

Create a line as usual:

    `const line = new LeaderLine(elem_1, elem_2, options);`

If you want to mark the line with the same `id` as LeaderLine:

      ```
     const all_svgs = document.querySelectorAll("svg");
     const this_svg = all_svgs[all_svgs.length - 1];
     this_svg.setAttribute("data-line_id", line._id);
     ```

You can retrieve the SVG element by `id` and change the line as needed (e.g. styling):

    ```
    document.querySelectorAll("svg").forEach(function(elem) {
        if(elem.getAttribute("data-line_id") === id) {
              // do something with elem
               elem.style.fontSize = "22px";
        }
    })
    ```

Obviously if you have other SVGs in your application you'll need to get a little more refined than `SelectorAll("svg")` but you get the point.

**Comment by anseki** [comment]
Hi @sean-mcclure, thank you for the information. :smile:

**Comment by anseki** [comment]
BTW, the loop (`forEach`) is not required and that is not good for the performance.
You can use `document.getElementById(ID)` instead.

**Comment by anseki** [comment]
Also, if you think that performance is important, use `getElementsByTagName` instead of `querySelectorAll`.

**Comment by sean-mcclure** [comment]
It's not an actual ID, it's data on the element. Hence the need to loop over the elements and find the correct one.

**Comment by anseki** [comment]
You can add actual ID by `element.id = ID` instead of `element.setAttribute('data-line_id', ID)`, and you can use `document.getElementById(ID)` for performance.
Or, if you really want to use fake ID instead of actual ID, you can use `document.querySelector('[fake-id="ID"]')` instead.
Anyway, the loop is not required and that is not good for the performance.

**Comment by AlexSkrypnyk** [comment]
@sean-mcclure 
Thank you for your response.
What you wrote is exactly what I explained: create a line and then get the last created SVG and add an attribute to it. But @anseki said that "that is not supported and that is deprecated.". What "that" is - I did not understand. I asked and did not receive a clear answer. Other comments describe exactly this way.

@anseki 
Can you please please write a piece of code here that can be used to set an arbitrary attribute on the SVG.

Could you please not reference any other comments because they are all referencing each other and this whole thing very confusing. 

The question is simple: I have to create 10 lines and then I want to access these lines to remove them. How do I access them according to your official documentation?

**Comment by sean-mcclure** [comment]
@AlexSkrypnyk the approach is supported since it doesn't depend on LedaerLine; it is vanilla JavaScript. As long as LeaderLine continues to implement their lines as SVG this approach will work.

**Comment by anseki** [comment]
@AlexSkrypnyk,
Sorry, I can't write that here because that is not supported and that is deprecated, and I already wrote it.
If you really want it, you can find a unsupported way in past issues, and you seem to have already done. Of course you can use that regardless of whether it is supported or not, if you really want it and understand DOM and SVG.

Anyway, maybe you don't require LeaderLine. LeaderLine is a library to draw a line easily by wrapping SVG and others. In other words, the library was designed for handling SVG and others instead of user. Therefore, it may be broken when user changed the SVG.
If you want to access to SVG and do something, you should use another library to do that. You can find better libraries such as [Snap.svg](http://snapsvg.io/). Or, you can do that without library if you want simple lines, this is better choice.

@sean-mcclure,
Thank you for the information. :smile: 
Note that @AlexSkrypnyk's approach is very faster than @sean-mcclure's approach. For example, `querySelectorAll` is slower than `getElementsByTagName` as I said.
https://www.google.com/search?q=getelementsbytagname+queryselectorall+performance
It was reported, that is nearly 8 times slower in some browser. (Some modern browsers try to improve it by calling `getElement*` instead of `querySelector*` inside engine if possible.) And also, the loop that makes the program slow is not required.
@AlexSkrypnyk's approach is very simple and fast.

**Comment by sean-mcclure** [comment]
Hence the reason I said he could get more refined with his approach. Regardless, a simple comment on an approach is not meant to show the most efficient way possible. Besides, everyone's context is different. 

In any case, all of this is only because a proper id reference has not been made available in this library. It should be added. Not being able to directly access the added svg is very odd for open source. 

I recommend people make their own line library. Not that difficult.
