### ISSUE TITLE
LeaderLine not drawing lines

### ISSUE THREAD

**Issue by Rick-415** [anseki/leader-line#222]
I'm embarrassed to say I can't figure out why I can't get LeaderLine to work. I have a bare minimum html page with two <div> elements and trying to use the leaderline.min.js in its simplest form to draw a line between the two.  I have loaded the leaderline.min.js file in my header and verified its loaded.  I'm new to asking for help - should I post my code?

**Comment by anseki** [comment]
Hi @Rick-415, thank you for the comment.
Could you show your code by using e.g. https://jsfiddle.net/ ?

**Comment by Rick-415** [comment]
It looks like you've made this program very easy to use, so this must be something very simple.

https://jsfiddle.net/rick415/evw7ryq8/

**Comment by anseki** [comment]
Your code fails the loading `leaderline.min.js` because the URL doesn't exist.
Try this: https://jsfiddle.net/qyc8ugs0/

**Comment by Rick-415** [comment]
It does exist - I have uploaded it to the js folder on my server (noted in the header), and I confirmed that it is loading.  Is there an outside location of that file that we can load it from to test?

**Comment by Rick-415** [comment]
Where is it loading leaderline.min.js from on your jsfiddle example?

**Comment by Rick-415** [comment]
https://jsfiddle.net/rick415/evw7ryq8/6/

**Comment by anseki** [comment]
Your code fails the loading `leaderline.min.js` because the URL is not safe (not HTTPS). This bug in your code is unrelated to LeaderLine.

When you develop something, you should use DevTools of web browser. It helps you very much, and nobody can develop well without the DevTools.
Press <kbd>F12</kbd> to open DevTools window while your browser is accessing the web page. And click "Console" tab.
The Console prints messages from the web browser. Error messages indicate what are bugs in your code.
That says:
```
http://www.stjoememorialpark.com/search-dev/js/leader-line.min.js has been blocked, it is insecure request. It must be served over HTTPS.
```

**Comment by Rick-415** [comment]
Thank you so much for your help.

**Comment by anseki** [comment]
:smile:

**Comment by anseki** [comment]
FYI, you can specify `//www.stjoememorialpark.com/search-dev/js/leader-line.min.js` instead.
This means using the same scheme as current web page. That is, `https` is used automatically.

**Comment by Rick-415** [comment]
Thanks so much for your input.  I guess I may have closed this too soon, though.

If I change to https on JSfiddle it works, but only if I move the js script to the js window below. Is there something wrong with including that js script in the html body?

I have verified that I have a valid SSL certificate on my site and changed the reference to the js folder to include "https" but still does not work. The DevTools reports no issues.

**Comment by Rick-415** [comment]
https://stjoememorialpark.com/search-dev/test.html

**Comment by anseki** [comment]
You have to write HTML code as only content in `<body>` element because those are added by JSFiddle.
You have to write like this: https://jsfiddle.net/qyc8ugs0/

Also, you have to specify MIME-type for `type` attribute of `<script>` element if you want to specify.
For example:
```html
<script type="text/javascript">
```
However, this is default type, then you should write like this:
```html
<script>
```

**Comment by anseki** [comment]
And also, you don't have to write `https`, you should write like `js/leader-line.min.js`.

**Comment by Rick-415** [comment]
I can't believe it, but that fixed it.  All I had to do was add the "text/javascript" to the script tag.  I always thought that was optional since it is the default.  Thank you for your patience with me and your wonderful program.

**Comment by anseki** [comment]
As I said, the `text/javascript` is default, therefore you don't have to add that, and that is old style. `<script>` is better.
Anyway, I'm glad if I could help you. :smile:
