### ISSUE TITLE
Leader-line Cannot read property "right" of null

### ISSUE THREAD

**Issue by Nickfis** [anseki/leader-line#230]
Hi,

First of all thank you so much for creating this awesome library! It helped me out a lot and saved me a lot of time. 
I have one small issue, which has already been mentioned [here before ](https://github.com/anseki/leader-line/issues/53). In that case you helped the user out by solving his issue in a JSfiddle but I haven't fully understood where the problem is actually coming from. 
I've created a drag&drop timeline which works well, until you resize the window. I am redrawing the Leader-Line's on resize and also remove the svg Elements from the DOM before redrawing but somehow I still get the error Leader-line `Cannot read property "right" of null` as well as `A disconnected element was passed`. 
You can see my code [on this codepen](https://codepen.io/nickfis92/pen/poevBQG) 

I'm sorry for asking you, since it's probably just a code in my bug and not anything to do with the library you created, but I've spent hours on it and I just don't understand what's happening.

Thank you!

**Comment by anseki** [comment]
Hi @Nickfis, thank you for the comment.
As the message said, that bug of your code is caused by "A disconnected element was passed". And this is specification of HTML/DOM, it is unrelated to LeaderLine.
Since you broke elements that construct an object as a library, the library instance is no longer able to work.
You have to use `remove` method to remove that instead of removing the elements forcibly by using DOM API.
See document: https://anseki.github.io/leader-line/#remove

**Comment by Nickfis** [comment]
Oh of course! I tried that .remove() method on the created lines but was still deleting the elements from the DOM with the normal DOM Api, which is why that failed.
Thanks a lot! Everything works as expected now.

**Comment by anseki** [comment]
:smile: 
FIY, your example seems to have more bugs. For example, wrong HTML syntax, wrong CSS syntax, wrong JavaScript syntax, meaningless code, wrong logic, etc.
Especially, it may be performance serious degradation because it rebuilds DOM repeatedly even if it is unneeded. For example, your app may crash when the window is resized repeatedly.
You can avoid the meaningless rebuilding DOM. For example: https://codepen.io/anseki/pen/KKWpMva
