### ISSUE TITLE
Feature request/ Speed Improvement in document end attachment

### ISSUE THREAD

**Issue by animaone** [anseki/leader-line#248]
I have done some tests with multiple SVG rendering in Firefox and I noticed that there is a speed bottleneck that can occur when you append multiple SVGs to the body's document one by one.

The recommended way of doing such task is to create a sub-element such as a document.createElement("div"),
them, append all LeaderLines created to this element, 
and finally attach the sub-element to the document body at once, instead of attaching individual SVGs.

I noticed a significant speed improvement when doing this, and this improvement is independent of using threads/events.

There is some way I can get the SVG element from LeaderLine without attaching it directly to the document end?

Actually I am looking for at least to some way of doing such thing, and if it is not possible, a "hack" in the source code that can override some method.

**Comment by animaone** [comment]
The following link may explain correctly what is happening:

https://stackoverflow.com/questions/8913419/is-chromes-appendchild-really-that-slow

**Comment by anseki** [comment]
Hi @animaone, thank you for the comment.
The LeaderLine is not used for a page requiring too many lines, then it works without problem in almost cases such as a page requiring a hundred lines. Also, if you want a page requiring more lines, you should not use the library because there are inefficient processes other than the appending elements.
Since this library was written for making SVG easily, that has to be simple API. And also, you can use SVG instead.
So, of course I will consider the feature if more requests come.
Thank you for your suggestion. :smile:

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.

**Comment by anseki** [comment]
Thank you for the proposal about the option.
Honestly, I don't know the effectiveness of the manual adding DOM and demand for that.
Now, I think that the library is used for simple cases (they want to just draw lines easily).
I'll rethink that if more requests come.
Thank you for your suggestion. :smile:
