### ISSUE TITLE
Zoom Issue

### ISSUE THREAD

**Issue by andyhoyle** [anseki/leader-line#279]
Previous tickets with same issue #47 and #113  have been raised previously.

When zooming in and out, the size and position of the line is not updated, event when calling .position()

Here is reproduction steps:

https://jsfiddle.net/97etdyr6/

**Comment by anseki** [comment]
Hi @andyhoyle, thank you for the comment.
The `zoom` property is not supported by some browsers, and usage of the property in your CSS code is incorrect.
https://developer.mozilla.org/en-US/docs/Web/CSS/@viewport
You should use `scale` CSS function instead. And that has to be specified for `<body>` as viewport.
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/scale()
Also, lines are not positioned correctly in an element having `scale` because that changes `transform`.
If you want to change size of the lines and elements, you should change each size of parts, or add SVG for lines.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.

**Comment by anseki** [comment]
FYI;
https://jsfiddle.net/jp2yout4/
