### ISSUE TITLE
Possibility of attaching events to leaderlines

### ISSUE THREAD

**Issue by guirama** [anseki/leader-line#29]
Hi,

I went through the documentation and didnt come across about attaching events to lines.  I mean events like right click, mouse over etc.

Are there event handling support added already or

is there a possibility to add 'id' attributes to lines, so then it is possible to bind events to individual lines.

Best Regards

Indunil

**Comment by anseki** [comment]
Hi @guirama, thank you for the comment.
You can use `SVGDOM#addEventListener` to add event listeners.
These may help you:
https://github.com/anseki/leader-line/issues?q=is%3Aissue+is%3Aclosed+event
Note that it is not recommended because of usability for users (a line is usually thin), and also, it is not supported.

**Comment by guirama** [comment]
Hi,

Thanks a lot. I thoght about highlighting linr on hover and binding a context menu - for example giving user an option to delete the line via context menu.

I'll check with your suggestion.

Best Regards

Indunil

**Comment by anseki** [comment]
:smile:
