### ISSUE TITLE
Logic of building poligon shape for area anchor

### ISSUE THREAD

**Issue by Smithpovvi** [anseki/leader-line#297]
Please, help. tell me what is the logic of construction of area anchor with params(polygon). What order are the points in? Where does construction begin?

**Comment by anseki** [comment]
Hi @Smithpovvi, thank you for the comment.
The drawing a polygon starts with first point in [`points`](https://anseki.github.io/leader-line/#points) option that you specified, and it draws in the order of your array.

**Comment by Smithpovvi** [comment]
@anseki I specify 1 point, then it goes in the order of the array. Okay. What is the coordinate plane relative to? Relative to the previous point?

**Comment by anseki** [comment]
Relative to the top-left corner of the specified `element` option.
I recommend you to read [the document that I told you](https://github.com/anseki/leader-line/issues/297#issuecomment-1033931984) because all your questions till now are already explained in the document, and you can save your time, and mine. :smile:

**Comment by Smithpovvi** [comment]
Ahh yes thanks))

**Comment by anseki** [comment]
I welcome any question, if you have it after reading the document. :smile:
