### ISSUE TITLE
ERROR TypeError: Cannot read properties of undefined (reading 'curStats')

### ISSUE THREAD

**Issue by sachinbahal294** [anseki/leader-line#304]
Hi @anseki , I am facing one issue while repositioning the lines.
Here's my code : 
`if(this.allLines[this.stepId] && this.allLines[this.stepId].length > 0){`
            `this.allLines[this.stepId].forEach(element => {`
			`// it has element.src, element.tgt and element.line`
                `if(element.src && element.tgt){`
                    `setTimeout(() => {`
                        `element.line.position();`
                    `}, 500);`
                `}`
           ` });`
       ` }`

**Comment by anseki** [comment]
Hi @sachinbahal294, thank you for the comment.
I couldn't understand your code because that is just a mere part of program. For example, nobody knows what the `this.allLines[this.stepId]` contains. And more things are hidden.
However, I think that the `this.allLines[this.stepId]` array contains already removed lines. You should remove the "removed lines" from the array. In other words, you called `position` method of already removed line, then the error should be thrown.

**Comment by sachinbahal294** [comment]
Thanks @anseki for quick reply....
is there any flag or property available under line that shows if its removed or not ?

**Comment by anseki** [comment]
This is an example:
```js
// Remove a line.
element.line.remove();
element.line = null;
```
```js
// Reposition a line.
if (element.line) { element.line.position(); }
```

**Comment by sachinbahal294** [comment]
great thanks @anseki

**Comment by anseki** [comment]
Removing the element from the array by using [`splice`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice) method is better if you no longer need `element.src` and `element.tgt`.
So, could you close this issue?

**Comment by sachinbahal294** [comment]
sure thanks
