### ISSUE TITLE
Provide more build output formats

### ISSUE THREAD

**Issue by oliversalzburg** [anseki/leader-line#310]
I've recently come across leader-line and plain-draggable and absolutely love them. I noticed that plain-draggable can easily be `import`ed into my code, while leader-line need to be included at the top of the document.

I was wondering if it would be possible to build leader-line in the same way plain-draggable is built to make integration with bundlers easier.

I could probably work on a PR for this, if that would help :)

**Comment by anseki** [comment]
Hi @oliversalzburg, thank you for the comment.
As you said, source code of LeaderLine was not written with supporting `import/export` because that is very old. For example, that uses `var`. That is, it was not written with modern code such as ES2015.
Therefore, I think that it should be rewritten with modern code that supports `import/export` rather than forcibly adding `export` that breaks the code.
Of course I'll think about the rewriting it if more requests come.

**Comment by oliversalzburg** [comment]
That makes sense. For now, I'll use it as-is. Thanks for the great work :)

**Comment by anseki** [comment]
:smile:

**Comment by ViltsuV** [comment]
> I'll think about the rewriting it if more requests come.

Please do! :writing_hand: :slightly_smiling_face:

**Comment by anseki** [comment]
Hi @ViltsuV, thank you for the comment. :smile:
