### ISSUE TITLE
Set/update line start/end using top,left (x,y) position?

### ISSUE THREAD

**Issue by mariusrosoga** [anseki/leader-line#313]
@anseki is it possible to set/update the line start & end position by providing the element left, top  (x,y) position instead of the element id?
So, instead of using :
`line = new LeaderLine(start, end, {  color: 'red'});`
to use:
`line = new LeaderLine({x: 32, y:66}, {x: 77, y:57}, {  color: 'red'});`

Also, is it possible to update line start & end in another way except by calling the `line.position()` method?
Preferable to update the new top, left (x,y) position on the line start/end on drag move.

I've read the documentation, but I didn't found any other way.

Great library by the way :)

**Comment by anseki** [comment]
Hi @mariusrosoga, thank you for the comment.
You can specify [`pointAnchor`](https://anseki.github.io/leader-line/#pointanchor) instead of an element for the start/end option. Then you can indicate points of something including `<body>` element (i.e. anywhere in the document).
Also, you can update the line for moved elements.
(Sorry, I couldn't understand the "except by calling the `line.position()` method" you said.)

**Comment by mariusrosoga** [comment]
@anseki, but doesn't pointAnchor require the element? in the documentation example, I can see something like this `LeaderLine.pointAnchor(element2, {x: 16, y: 32});` I was looking for an option only to specify the top-left corner position of the start/end line {x: 120, y: 230}, and no other element reference.
Maybe I'm missing something here :)

**Comment by anseki** [comment]
Sorry, my English is poor.
Do you mean that the `{x: 120, y: 230}` that you said is not coordinates that are relative to the document? I thought that you want to specify `x` and `y` that indicate a position that is relative to the top-left corner of the document.
Could you explain about what the "the top-left corner position of the start/end line {x: 120, y: 230}" that you said mean?

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
