### ISSUE TITLE
Overlapping Lines

### ISSUE THREAD

**Issue by Adyasha8105** [anseki/leader-line#330]
You can see the lines are overlapping over the table (and the z-index is also not working) and the hover property is also creating some problems while dragging the table.

The main issue is How to hide the lines behind the tables?

<img width="362" alt="Screenshot 2022-05-24 at 6 44 25 PM" src="https://user-images.githubusercontent.com/54095539/170043640-97b6cd52-f530-4c1a-bbe6-c730e34ae7b0.png">
.

**Comment by ahmedshaaban00** [comment]
@Adyasha8105 I used to face the same issue, It's basically because the author decided to place the lines inside the body element directly without giving the option to choose where to place the lines...
Z-index will not work because the lines are in the top of the DOM tree. You should find a workaround to place them inside a custom wrapper placed within the same level as the other elements that you have.

I was able to achieve that but there're still some issues I'm trying to fix regarding this and will update you when It's done.

**Comment by anseki** [comment]
Hi @Adyasha8105, thank you for the comment.
This may help you: https://github.com/anseki/leader-line/issues/48
If your `z-index` doesn't work, maybe you should understand the ["stacking context"](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context), it is unrelated to the SVG element existing in the `body` element.

**Comment by anseki** [comment]
No reply came, but the issue was closed because it was already solved maybe. :smile:
