### ISSUE TITLE
MIN_GRID_LEN dynamic ? 

### ISSUE THREAD

**Issue by calumk** [anseki/leader-line#373]
Hi, I have an applicaiton where I need a diffferent (smaller) grid size for the grid line style (small distances between nodes)

At the moment, I can achieve this by re-building the library with `MIN_GRID_LEN = 15`

I am assuming this is the only way to do this at the moment? - There is no way to dynamically change the grid size on creating a new line? 

Cheers

**Comment by anseki** [comment]
Hi @calumk, thank you for the comment.
As that was already mentioned in past issue (https://github.com/anseki/leader-line/issues/133), the `MIN_GRID_LEN` has to avoid being accessed because that obviously breaks the API design.
If you really want to do that, you can fork and customize the library to make a special one for your app, as you said.

**Comment by calumk** [comment]
Ha! @anseki - sorry - that was actually me that raised that old issue.
2 years later working on a different project, and I came across the same problem. 

Sorry for wasting your time.

I have forked the library and solved both this and https://github.com/anseki/leader-line/issues/374

**Comment by anseki** [comment]
It's ok. :smile: 
Could you close this issue?
