### ISSUE TITLE
performant css transformations and position updates

### ISSUE THREAD

**Issue by HFx6** [anseki/leader-line#381]
What's the recommended way to perform css transformations on the leader-line svgs in order to keep them consistent with their connected items?

My DOM hierarchy is similar to 
```
- canvas
   -  node-wrapper
      - node 1
      - ...
      - node n
      - leader-wrapper
         - line 1
         - ...
         - line m
```
I have moved the svgs into their owner wrapper after line creation to make moving them easier.
An example view can be seen here of how a setup could be constructed where the "canvas" is panned across (in reality is just moves the node-wrapper position as the user drags)

before transform |  after transform
:-------------------------:|:-------------------------:
<img src="https://user-images.githubusercontent.com/43940641/203904082-ebd95c19-4650-48f7-aa7b-66405b9e3013.png" width="300">  |  <img src="https://user-images.githubusercontent.com/43940641/203904139-7b84bc26-e298-45e7-9f0d-2b3eb69dca8f.png" width="300">

The issue is "solved" to call `line.position()` on pan, but its not performant and lags with only a handful of lines. Is there a better way to solve this with leader-line?

I'm using this in a react environment, I keep reference to all connections, nodes and line instances.
I had made my own bezier connector line solution where each socket position used a reference `offset{}` based on the current "pan", which very efficient when moving many connections, can leader-line do something similar?

**Comment by anseki** [comment]
Hi @HFx6, thank you for the comment.
Sorry, my English is poor.
Do you mean that LeaderLine is slow?
If so, your better way to solve the issue is the using another library as helper drawing. If you want to draw lines by using SVG, there are great libraries such as [Snap.svg](http://snapsvg.io/) to help handling SVG.
Because the LeaderLine is a library for beginners that allow to draw lines easily. Therefore, the library is too big and it has many method. Also, it creates many elements that might be unused.
Then, it is unsuitable for an app that requires high performance.

**Comment by HFx6** [comment]
Thanks for the quick response @anseki 

> Do you mean that LeaderLine is slow?

Sorry if I my explanation wasn't very clear 😅, calling `position()` on every `pointermove` event is quite slow when you have more than a couple LeaderLines displayed. The alternative is to set an offset to the anchor or socket automatically that matches the transform of the element(s), but i'm not sure if LeaderLine supports this. Could there be another way i am missing?

if it helps, this fiddle you made https://jsfiddle.net/y35sc1th/ is similar to what I have in my environment, however, the wrapping div of the "nodes" is infinite and allows you to pan around infinitely.

**Comment by anseki** [comment]
> calling position() on every pointermove event is quite slow when you have more than a couple LeaderLines displayed.

Do you mean that LeaderLine is slow?
If so, your better way to solve the issue is the using another library as helper drawing.
Typically, an animation is performance degradation regardless of the LeaderLine if your code does something in an event handler that is fired too frequently (e.g. `pointermove`).
This may help you: https://github.com/anseki/anim-event/
You should see that the example in JSFiddle is not slow. The example uses AnimEvent above.

**Comment by HFx6** [comment]
I will try a couple more attempts using your anim-event lib, and try some more performant management of the LeaderLines first. Bit of a hassle to reduce my react code to jsfiddle to show off this specific thing; because of many things that could be causing this, i will try and investigate more to see how I can I best replicate this node editor.

**Comment by anseki** [comment]
Sorry, I couldn't understand your words well.
I think that you try to fix your code because it might have a problem about "memory leaking" regardless of the LeaderLine.
When you fixed the bug, the issue that make LeaderLine slow should be solved.
If your app is still slow nevertheless, you had better use another library as I said first (https://github.com/anseki/leader-line/issues/381#issuecomment-1327112487).

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
