### ISSUE TITLE
How to use event listeners (Issue being unrelated to LeaderLine)

### ISSUE THREAD

**Issue by gumireddyprashanth** [anseki/leader-line#57]
Hi Anseki,

This is the code i'm working on.
[https://jsfiddle.net/Ljwc0729/](url)

Im using 2 libraries 
1. Panzoon Jquery 
2. Mousewheel jquery

**What I'm trying achieve**
- I have 4 boxes in page which im trying connect each other with lines (To tell from which box the data is flowing to which).
- And these individual boxes can be dragged/zoom-zoomout.
- Along with the drag and zoom the lines should move along the boxes.

**Where I'm facing the Issue**
- When i click on build for the first time, the boxes are connected with the lines and drag and zoom are working fine.
- But when i click build for the second time, a new set of boxes and lines are drawn, but when i try drag and zoom, lines are not getting re-positioned to the dragged position.

Hope you understand the problem.

Thank you

**Comment by anseki** [comment]
Hi @gumireddyprashanth, thank you for your comment.
So, that seems very simple issue. I found problems.
I tried to read your code, then... Sorry, your code is hard to read (e.g. strange indent).
See: https://github.com/anseki/leader-line/issues/56#issuecomment-504367685
This code seems almost the same as [previous your code](https://github.com/anseki/leader-line/issues/56#issuecomment-504299523). Is it right?
Remember, the correctly writing will help you, me and more. Also, you can save your time and my time.

**Comment by gumireddyprashanth** [comment]
Hi Anseki,

I hope i can write the best code, but, i'm still learning (intern).

New fiddle - [https://jsfiddle.net/6udow35q/2/](url)
With Updated Comments, and Indents.

I wish you be my guru.

Thanks

**Comment by anseki** [comment]
I strongly recommend a code editor such as [Visual Studio Code](https://code.visualstudio.com/) that checks and fixes your code automatically to you.
Unreadable code makes bugs and problems. In other words, the cause of this issue may be your code style. Therefore I repeatedly recommended writing code correctly **for you**, not for me.

Anyway, you will understand this issue by these steps:

1. Very basically, you should use "Developer Tools" when you debugs or inspects any web-app for web browser. For example, if you are using Google Chrome, press `F12` key.  
In your fiddle, After you clicked the button twice and drag a blue box, you will see a message in "Console" in the Developer Tools: "TypeError: Cannot read property 'options' of undefined".  
Then, you can get why your code didn't work (also, what, where and when).
2. See this: https://jsfiddle.net/ux6pykgL/  
The `line.obj.position()` was commented out. Of course the lines are not updated, the error above was avoided for test. This means that this issue is unrelated to LeaderLine.  
Also, pay attention to two `console.log` lines. These should print a message when each of your event listeners (`panzoomchange` or `mousewheel`) is called.
3. After open the console, click the button **only once**, and move the mouse pointer to a gray box, and spin the mouse wheel only **one notch**. Then, you will see the each message from two event listeners. This is expected result.
4. Then click the button again, and move the mouse pointer to a gray box, and spin the mouse wheel only **one notch**. You will see strange result.

The event listeners were added every time without removing old one when the button was clicked, and also, those are added per all lines. Therefore, many event listeners (different things) were added and called even if the line was already removed. This is wrong and meaningless behavior regardless of the error.
That is, you have to add the event listeners only once.

Also, other problems:
* As I said (https://github.com/anseki/leader-line/issues/56#issuecomment-503541402), replacing HTML code for removing and adding boxes is not good idea.
* Some code seem to have no meaning. e.g. `.show`, `.find` and `.parent` that are executed every time.
* The `panzoomchange` event never be fired except the blue boxes because the element that the event was attached to has no size.
* The figure is not draggable except the blue boxes because the element that is passed to `panzoom` method has no size.
* Two boxes jump upward when you drag it or spin the mouse wheel because origin of coordinates is changed.

For example: https://jsfiddle.net/56ceo32z/

**Comment by gumireddyprashanth** [comment]
Hi Anseki,

Installed Visual Studio Code with try to switch my project to it and start using debugger/console.

Thank for step by step guide and making me understand what exactly the problem was, and helping me to understand/learn how to debug.
Ill try to rewrite the code from the start to follow the procedure and and to understand what really going on in the code.
Ill remove **.show** **.find** and **.parent** in the code and simplify it further.

I have to learn more about events and there right use.

Thanks for the help Anseki, greatly appreciated and thanks for allotting you time.

Regards

**Comment by anseki** [comment]
Note that the example I wrote doesn't solve the problem about replacing HTML in the problem list that I indicated.
I don't know your app, then I conjecture it. Do you want to do?:
- Show one of figures per clicking the button.
- A figure has boxes that is put on specific position, and lines that connects specific boxes.

**Comment by gumireddyprashanth** [comment]
Hi Aneski,

Replacing the HTML and Drawing lines is working now after removing all events attached.
Your fiddle worked perfect.

Replacing the HTML was upon user selection.

1. User can select maximum 4 countries out of 100 in a dropdown(MultiSelect).
2. When user selects 4 different countries, 4 boxes are draw (Using which i construct the HTML with Values of 4 Countries) .
3. But the user can again go back and change the 4 countries to different countries. (so i'm clearing of the existing 4 countries html and replacing with new HTML.)
4. I'm updating the lines along with it.

I'm an intern in a bank, they gave me this project. 
I'm a newbie to JavaScript, but its exciting. :)

Regards

**Comment by anseki** [comment]
That changes only boxes and lines, right?
The replacing HTML is usually avoided because the rendering new document from HTML code takes a high cost.
Also, it might make more problems. e.g. it can include any elements, it makes disconnected elements, etc.

This example removes existing items and lines and adds new items and lines when the button was clicked, instead of replacing the HTML code.
https://jsfiddle.net/04dvgfnj/

And, this is more better if the figures are static.
This design is called "paging". It creates all pages in initialization, and it only switches the shown page when the button was clicked.
https://jsfiddle.net/04dvgfnj/1/

**Comment by anseki** [comment]
BTW, if you will use the Visual Studio Code, install ESLint extension also to check and fix your code.
https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint

**Comment by gumireddyprashanth** [comment]
> 
> 
> That changes only boxes and lines, right?
> The replacing HTML is usually avoided because the rendering new document from HTML code takes a high cost.
> Also, it might make more problems. e.g. it can include any elements, it makes disconnected elements, etc.
> 
> This example removes existing items and lines and adds new items and lines when the button was clicked, instead of replacing the HTML code.
> https://jsfiddle.net/04dvgfnj/


This seriously works, ill start implementing this.
Let me try how its gonna work in my scenario.
The prime concern was how to replace/construct the HTML on the second time.
Will try this out.

Regards

**Comment by gumireddyprashanth** [comment]
Hi Anseki,

Below is the project im working on, 
![est](https://user-images.githubusercontent.com/26119515/60070486-80697800-9734-11e9-98b3-421d7d1df700.jpg)

This is the JSON to Draw HTML. There are 3 loops within each other to draw the data.
![json1](https://user-images.githubusercontent.com/26119515/60070705-3339d600-9735-11e9-94d3-f1d542827305.JPG)

This the JSON to draw the lines between the elements.
![draw1](https://user-images.githubusercontent.com/26119515/60070771-7ac06200-9735-11e9-8923-f9dd7af62086.JPG)

1. When the user selects multiple options from multiple dropdowns the combination might be anything, when he clicks "Build" the values/json i get from backend is unknown or might change according to time.
2. I'm Drawing lines between children, not the parent blocks (ex. Financial Ratios Engine and RWA Engine), its the children level, when the user click build again there children might change.

It is true that clearing the HTML each time on click of build is lagging my page, there might be n number of box's that can come up on the page. So every time i get JSON data im clearing the old one and replacing with new.

I'm unsure how to handle the HTML in this case.

Regards

**Comment by anseki** [comment]
Are all items static defined in the JSON?
And, does the user dynamically select some items from item list above?

**Comment by gumireddyprashanth** [comment]
Level 2 items in json are static(No Shock, Static Output, From Engine etc ), only the third level is dynamic, values may differ each time the user changes the dropdowns.

![image](https://user-images.githubusercontent.com/26119515/60083316-21ffc200-9753-11e9-88b2-862ca7963bbd.png)

All the dropdowns have more than 50+ options dynamic. if i select a value in first dropdown, the second dropdown values will change depending upon first one.

**Comment by anseki** [comment]
I mean, items in each item list are static. A specific list is only replaced when upper level option is changed.
Anyway, if items that should be shown are selected from static list, those have not to be created and removed dynamically.
For example: https://jsfiddle.net/z9L2dh4r/
Note that this chooses items that are connected by lines randomly because I don't know the rules of drawing lines.
This only switches showing and hiding of each item. It can reduce the job and it can be simple logic.

**Comment by anseki** [comment]
This example switches showing and hiding of each item.
If items in each list are static, you can switch showing and hiding of each list (i.e. parent element) instead of item.

**Comment by gumireddyprashanth** [comment]
> 
> 
> I mean, items in each item list are static. A specific list is only replaced when upper level option is changed.
> Anyway, if items that should be shown are selected from static list, those have not to be created and removed dynamically.
> For example: https://jsfiddle.net/z9L2dh4r/
> Note that this chooses items that are connected by lines randomly because I don't know the rules of drawing lines.
> This only switches showing and hiding of each item. It can reduce the job and it can be simple logic.

Wow.. i think this is the way to do it. 
Just need some time to dig this out, and make it work.

Can i keep this issue open for a day?

**Comment by anseki** [comment]
Ok, please close this issue after a few days if you want.
However, you can access this issue at any time even after this was closed.

**Comment by gumireddyprashanth** [comment]
Hi Aneski,

Thank you mate, i have started using the the same logic as u did.
its a huge thing for me to comeplete this project.
Will definitely will get back to you if i need help.

Thank you :)
Regards

**Comment by anseki** [comment]
:smile:
