### ISSUE TITLE
Cannot read property 'curStats' of undefined

### ISSUE THREAD

**Issue by mehuljariwala** [anseki/leader-line#71]
Hey,
Sometimes i get this error is there any way to handle this error ?

**Comment by anseki** [comment]
Hi @mehuljariwala, thank you for the comment.
Sorry, my English is poor.
Could you explain more about that?

**Comment by anseki** [comment]
No reply came, then I close this abandoned issue.

**Comment by MarlenePF10** [comment]
Hi anseki!

I'm using your library to link some divs in two different columns. Then I erase these arrows before an ajax call that brings a partial view. Here I can link other bunch of divs in other two columns.
In the first page works everything fine, the issue comes when I press the button to go to the second page. I can draw the arrows in this second page but when it's time to erase them before the ajax call, appears the issue.

I try another thing, I did not draw arrows in the first page, click next and draw arrows in the second page (where appears the issue) and it totally worked. It seems like this only can be done once (?).
I attach a screenshot of issue.

Hope you can help me,
thanks a lot.
Marlene
![issueLeaderLine](https://user-images.githubusercontent.com/72233615/94872132-6c212a00-0411-11eb-924c-f950910dae42.png)

**Comment by didacus** [comment]
@anseki Can we open this issue? I am getting the same error when trying to unmount the component when changing pages. Is this the correct way to unmount the lines?

**Error**
**TypeError: Cannot read property 'curStats' of undefined**

**(anonymous function)
src/components/diagram.js:192**

`  componentWillUnmount() {
    setTimeout(function () {
      if (mediaQuery.matches) {
        if (allLines && allLines !== undefined) {
          for (var i = 0; i < allLines.length; i++) {
            allLines[i].remove()
          }
        }
      }
    }, 1000)
  }`

**Comment by anseki** [comment]
Hi @didacus, thank you for the comment.
Your code seems to have a bug.
The error should occur when you try to re-remove a line that was already removed again.
Your code checks the `allLines !== undefined` but it doesn't update the `allLines`. That has to change it.
For example:
```js
componentWillUnmount() {
  setTimeout(function () {
    if (mediaQuery.matches) {
      if (allLines) { // meaningless: allLines !== undefined
        for (var i = 0; i < allLines.length; i++) { allLines[i].remove(); }
        allLines = null; // This means that lines were removed.
      }
    }
  }, 1000)
}
```

**Comment by didacus** [comment]
@anseki thank you for your solution. It seems to work. However, it has generated another issuer. The `allLines = null` are causing the following error `TypeError: Cannot read property 'push' of null`. If I remove that line, another error occurs where the lines are visible on the next page. Any ideas?

**Comment by anseki** [comment]
You can clear the array. This is more simple.
For example:
```js
componentWillUnmount() {
  setTimeout(function () {
    if (mediaQuery.matches) {
      for (var i = 0; i < allLines.length; i++) { allLines[i].remove(); }
      allLines.length = 0; // Clear
    }
  }, 1000)
}
```
