### ISSUE TITLE
Connecctions/Lines going outside of div

### ISSUE THREAD

**Issue by narendersaini32** [anseki/leader-line#83]
Hi Sir
Actually I am using the LeaderLine in my project and there is one case where the line/connection goes outside of div maybe because they are appended to body.
https://drive.google.com/drive/u/0/folders/1oMgxL_31sAQ4RN3EVPGRY0UkQhcQvfPL
Please check the above video

**Comment by anseki** [comment]
Hi @narendersaini32, thank you for the comment.
I couldn't access your video by an error that said I have no permission.

**Comment by anseki** [comment]
Could you show me an example by using  https://jsfiddle.net/ ?

**Comment by narendersaini32** [comment]
Sorry for inconvenience
you can check here https://drive.google.com/file/d/1zAUCpZWtt8UfReXXiXic8TQVnehdkLZS/view?usp=sharing

**Comment by narendersaini32** [comment]
and the actual app link is here https://flowchart1.netlify.com/

**Comment by anseki** [comment]
What is the difference between this and https://github.com/anseki/leader-line/issues/79 ?

**Comment by narendersaini32** [comment]
Yeah i tried that jsfiddle uses iframe by default

**Comment by narendersaini32** [comment]
![image](https://user-images.githubusercontent.com/50134025/69221102-7ee59400-0b9c-11ea-80dd-b7f5cc1ca37f.png)

**Comment by anseki** [comment]
?

**Comment by narendersaini32** [comment]
I mean I have three options

1. By default svg added to body but they are overlapping.
2. The js Fiddle example which uses iframe internally.
3. Append to a div which creates this above alignment issue.
My motive is to restrict the svg to a particular area it should not go outside of a div

**Comment by anseki** [comment]
Which example uses `<iframe>`?
And, do you mean that you don't want to use `<iframe>`?

**Comment by varunistar** [comment]
@anseki can u make like a different branch to append svg to particular element ? i cannot make use of <iframe>

**Comment by narendersaini32** [comment]
Like if you see this example https://jsfiddle.net/z5qw7a91/ the svg lines not going outside becuase its in an iframe of jsfiddle

**Comment by anseki** [comment]
No, that example doesn't use `<iframe>`.

**Comment by anseki** [comment]
@varunistar, you should make new issue for another question. This is @narendersaini32's issue.

**Comment by narendersaini32** [comment]
yeah that not uses but jsfiddle add iframe by default that was i am unable to generate the issue on jsfiddle

**Comment by anseki** [comment]
No, JSFiddle doesn't affect the code.
Run the example in your computer.

**Comment by anseki** [comment]
And, do you mean that you don't want to use `<iframe>`?

**Comment by narendersaini32** [comment]
yes iframe is not an option for me

**Comment by narendersaini32** [comment]
You can see iframe here in source code of jsfiddle and i can't use iframe in my case
![Screenshot from 2019-11-20 17-34-08](https://user-images.githubusercontent.com/50134025/69237637-1d352200-0bbc-11ea-9df8-e4f6dcde393e.png)
Is there is any alternative

**Comment by anseki** [comment]
No....
See this: https://github.com/anseki/leader-line/issues/83#issuecomment-555973774

**Comment by anseki** [comment]
You see that the example doesn't use `<iframe>`.

**Comment by anseki** [comment]
JSFiddle never add `<iframe>` into the code.
JSFiddle  only wraps the code by `<iframe>`.
See more the DevTools of your browser. And check where is the `<iframe>`.

**Comment by narendersaini32** [comment]
yeah sure

**Comment by anseki** [comment]
Did you understand that `<iframe>` was not added into the code?

**Comment by narendersaini32** [comment]
yes

**Comment by anseki** [comment]
Good :smile:
So, was this issue solved?
Or, do you have another question?

**Comment by narendersaini32** [comment]
in progress

**Comment by anseki** [comment]
I see.
Anyway, in your #79, you already saw that LeaderLine is working in scrollable `<div>` without `<iframe>` and without changing `top/left` of SVG, by examples (https://jsfiddle.net/op2gnk0t/ , #54).
I recommend reading those again.

**Comment by anseki** [comment]
No reply came, then I close this abandoned issue.

**Comment by gagwithgaffer** [comment]
@anseki the workaround you provided above using the wrapper (codepen example) did not work for me for a few reasons:

1 - I am using the plain-draggable js library for the elements drawn on the grid that is using your library to draw the connecting leader lines between them.
2 - I have a collapsable navbar menu located above the parent div that contains the leader lines and found that lines would move their positon when opening and closing the navbar above it.

![image](https://user-images.githubusercontent.com/51385414/205368342-ef262859-adb8-43f1-8eeb-e2674cbcb00b.png)

The only solution I have found to work is in fact putting the leader-line content into a iframe, its the only way to truly isolate the svg content controlled by your library without it having imapct on the parent page and its elements.

In my enviornment (.NET Core 6 Razor Pages Web App) I am using an iframe that points to another page within the same web app (same domain/origin) which allows me to give some isolation between the parent page and child contents that your library is being used for drawing the svg content. This adds a lot more work because of the all the necessary communication/cross referencing required between javascript functions that resides between both the parent page and emebdded js in the iframe.

**Comment by anseki** [comment]
Hi @gagwithgaffer, thank you for the information.
Sorry, my English is poor, and I couldn't understand that well.
However, that may help someone.
Thank you :smile:
