### ISSUE TITLE
Scrolling doesn't work with height 100 and overflowx hidden

### ISSUE THREAD

**Issue by rienheuver** [anseki/leader-line#87]
I found a bug with LeaderLine. It took me a while to trace it, but I think I narrowed it down. When setting the following css:
```
html, body {
   height: 100%;
   overflow-x: hidden;
}
```
And the page is long enough to cause scrolling, the lines will scroll along, instead of staying in position. A built a codepen here:
https://codepen.io/rienheuver/pen/eYYqLoO

Please let me know if I can supply any other helpful information.

**Comment by anseki** [comment]
Hi @rienheuver, thank you for the comment.
No, that is not bug.
LeaderLine is positioned based on the document. Since you forbade, that can't scroll. Then, the document that contains the LeaderLine is not scrolled.
You can specify this to forbid scroll only html.
```css
html { /* NOT `html, body` */
  overflow-x: hidden;
}
```

BTW, why you specify the `overflow-x: hidden` to the document? Maybe that is strange...
To avoid shown x-scroll-bar, you can specify e.g. `body { margin: 0; }`.

**Comment by rienheuver** [comment]
I had that in place to solve a bug with background colours I had. I was able to solve that differently though, so the lines are working as expected now. Thanks for the fast help!

**Comment by anseki** [comment]
:smile:
